name: Build, Test, and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Configure environment variables from secrets
        env:
          ORACLE_DB_USER: ${{ secrets.ORACLE_DB_USER }}
          ORACLE_DB_PASSWORD: ${{ secrets.ORACLE_DB_PASSWORD }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          RABBITMQ_USER: ${{ secrets.RABBITMQ_USER }}
          RABBITMQ_PASSWORD: ${{ secrets.RABBITMQ_PASSWORD }}
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
        run: echo "Environment variables set"

      - name: Give execute permission to Maven wrapper
        run: chmod +x ./mvnw

      - name: Build with Maven (skip tests)
        run: mvn clean install -DskipTests

      - name: Install Flyctl
        run: |
          curl -L https://fly.io/install.sh | sh
          echo "export PATH=\"$HOME/.fly/bin:\$PATH\"" >> $GITHUB_ENV
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Verify Flyctl installation and authenticate
        run: |
          export PATH="$HOME/.fly/bin:$PATH"
          fly auth token $FLY_API_TOKEN
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Deploy to Fly.io
        run: |
          export PATH="$HOME/.fly/bin:$PATH"
          fly deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
