name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure environment variables from secrets
        env:
          GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ORACLE_DB_PASSWORD: ${{ secrets.ORACLE_DB_PASSWORD }}
          ORACLE_DB_USER: ${{ secrets.ORACLE_DB_USER }}
          RABBITMQ_PASSWORD: ${{ secrets.RABBITMQ_PASSWORD }}
          RABBITMQ_USER: ${{ secrets.RABBITMQ_USER }}
      
      - name: Set executable permissions for Maven wrapper
        run: chmod +x ./mvnw

      - name: Run application tests
        run: ./mvnw test
